# Generated by Django 2.2.12 on 2020-05-27 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebooks', '0002_ebook_source_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='ebook',
            name='image',
            field=models.ImageField(default='', upload_to='images/'),
        ),
    ]
